"""initial schema

Revision ID: 09141f2247b8
Revises: 
Create Date: 2026-06-06 00:36:24.229600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09141f2247b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_participants', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_posts', schema=None) as batch_op:
        batch_op.drop_column('contact')
        batch_op.drop_column('budget')
        batch_op.drop_column('max_participants')

    # ### end Alembic commands ###
