"""add forum tags posts comments likes participants match

Revision ID: 85dde7863aac
Revises: 81cb36a3f950
Create Date: 2026-06-04 12:28:22.826030
"""
from alembic import op
import sqlalchemy as sa



revision = '85dde7863aac'
down_revision = '81cb36a3f950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
