"""add_urgency_to_event_posts

Revision ID: a0ca2765ee43
Revises: 85dde7863aac
Create Date: 2026-06-04 20:25:12.807393
"""
from alembic import op
import sqlalchemy as sa



revision = 'a0ca2765ee43'
down_revision = '85dde7863aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_posts', sa.Column('urgency', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_posts', 'urgency')
    # ### end Alembic commands ###
